### ISSUE TITLE
Passwords with special characters are parsed incorrectly, for example $ 

### ISSUE THREAD

**Issue by Alaahalawani** [imabedalghafer/domain-repro#5]
If the password for windows contains special characters like $, when it's passed via run command it will be parsed by the bash shell and thus the password will be incorrect when trying to join to domain.

**Comment by imabedalghafer** [comment]
Thank you Alaa for your feedback.
The issue has been fixed, by writing the password provided by the user to add a single quotas before sending it  via the run-command.

The fix will be applied in release 1.1 of the script
